FROM node:16

WORKDIR /app

COPY package*.json ./
RUN npm install -g json-server

COPY json-server.js ./

EXPOSE 3000

CMD ["json-server", "--watch", "db.json", "--middlewares", "json-server.js", "--host", "0.0.0.0", "--port", "3000"]
